/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee Filter Options */
        get: operations["employee_filter_options_api_v1_employees_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_api_v1_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/salary-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise Salary
         * @description Close the current pay record and open a new one from effective_from.
         */
        post: operations["revise_salary_api_v1_employees__employee_id__salary_revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bands */
        get: operations["list_bands_api_v1_bands_get"];
        put?: never;
        /** Create Band */
        post: operations["create_band_api_v1_bands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bands/{band_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Band */
        get: operations["get_band_api_v1_bands__band_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Band
         * @description Only bands no salary record was ever priced against can be deleted.
         */
        delete: operations["delete_band_api_v1_bands__band_id__delete"];
        options?: never;
        head?: never;
        /** Update Band */
        patch: operations["update_band_api_v1_bands__band_id__patch"];
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pay Summary
         * @description Headcount, payroll cost, base pay statistics, band compliance, median compa-ratio.
         */
        get: operations["pay_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pay Breakdown
         * @description The summary figures per department, country, level or role.
         */
        get: operations["pay_breakdown_api_v1_analytics_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/compa-ratio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compa Ratio Distribution
         * @description Distribution of base pay / band mid per group: quartiles and a histogram.
         */
        get: operations["compa_ratio_distribution_api_v1_analytics_compa_ratio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/band-compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Band Compliance
         * @description Employees paid below their band minimum or above its maximum, most severe first.
         */
        get: operations["band_compliance_api_v1_analytics_band_compliance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BandCompliance */
        BandCompliance: {
            /** Below */
            below: number;
            /** Within */
            within: number;
            /** Above */
            above: number;
            /** No Band */
            no_band: number;
            /**
             * Compliance Pct
             * @description within / employees with a band, percent; null if none have a band
             */
            compliance_pct: string | null;
        };
        /**
         * BandCreate
         * @description A band for one scope. Leave role_id and/or country_id out for a fallback band.
         *
         *     The currency is not sent: it is the country's currency, or USD for a band that
         *     applies in every country.
         */
        BandCreate: {
            /** Department Id */
            department_id: number;
            /** Role Id */
            role_id?: number | null;
            /** Level Id */
            level_id: number;
            /** Country Id */
            country_id?: number | null;
            /**
             * Min Amount
             * @description annual base, band currency
             */
            min_amount: number | string;
            /**
             * Mid Amount
             * @description annual base, band currency
             */
            mid_amount: number | string;
            /**
             * Max Amount
             * @description annual base, band currency
             */
            max_amount: number | string;
        };
        /** BandOut */
        BandOut: {
            /** Id */
            id: number;
            scope: components["schemas"]["BandScope"];
            department: components["schemas"]["DepartmentOut"];
            /** @description null: applies to every role in the department */
            role: components["schemas"]["RoleOut"] | null;
            level: components["schemas"]["LevelOut"];
            /** @description null: applies in every country, in USD */
            country: components["schemas"]["CountryOut"] | null;
            /** Currency Code */
            currency_code: string;
            /** Min Amount */
            min_amount: string;
            /** Mid Amount */
            mid_amount: string;
            /** Max Amount */
            max_amount: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BandPosition
         * @enum {string}
         */
        BandPosition: "below" | "within" | "above" | "no_band";
        /** BandRef */
        BandRef: {
            /** Id */
            id: number;
            scope: components["schemas"]["BandScope"];
            /** Currency Code */
            currency_code: string;
            /** Min Amount */
            min_amount: string;
            /** Mid Amount */
            mid_amount: string;
            /** Max Amount */
            max_amount: string;
        };
        /**
         * BandScope
         * @description Which parts of the cell a band is defined for, most specific first.
         *
         *     These are the only scopes band resolution looks up; a role without a country
         *     is not one of them.
         * @enum {string}
         */
        BandScope: "department+role+level+country" | "department+level+country" | "department+level";
        /**
         * BandUpdate
         * @description New amounts for an existing band. Its scope is fixed; create a new band instead.
         */
        BandUpdate: {
            /** Min Amount */
            min_amount?: (number | string) | null;
            /** Mid Amount */
            mid_amount?: (number | string) | null;
            /** Max Amount */
            max_amount?: (number | string) | null;
        };
        /** Breakdown */
        Breakdown: {
            by: components["schemas"]["Dimension"];
            /** Rows */
            rows: components["schemas"]["BreakdownRow"][];
        };
        /** BreakdownRow */
        BreakdownRow: {
            group: components["schemas"]["GroupKey"];
            /** Headcount */
            headcount: number;
            /** Payroll Cost Usd */
            payroll_cost_usd: string;
            /** Payroll Share Pct */
            payroll_share_pct: string | null;
            base_salary_usd: components["schemas"]["SalaryStats"];
            band_compliance: components["schemas"]["BandCompliance"];
        };
        /**
         * ChangeReason
         * @enum {string}
         */
        ChangeReason: "hire" | "promotion" | "merit" | "market_adjustment" | "correction";
        /** CompaBucket */
        CompaBucket: {
            /** Label */
            label: string;
            /**
             * Lower
             * @description inclusive; null = unbounded
             */
            lower: string | null;
            /**
             * Upper
             * @description exclusive; null = unbounded
             */
            upper: string | null;
            /** Count */
            count: number;
        };
        /** CompaRatioDistribution */
        CompaRatioDistribution: {
            by: components["schemas"]["Dimension"];
            /** Rows */
            rows: components["schemas"]["CompaRatioRow"][];
        };
        /** CompaRatioRow */
        CompaRatioRow: {
            group: components["schemas"]["GroupKey"];
            /** Employees With Band */
            employees_with_band: number;
            /** Avg */
            avg: string | null;
            /** P25 */
            p25: string | null;
            /** Median */
            median: string | null;
            /** P75 */
            p75: string | null;
            /** Min */
            min: string | null;
            /** Max */
            max: string | null;
            /** Buckets */
            buckets: components["schemas"]["CompaBucket"][];
        };
        /** CountryOut */
        CountryOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Currency Code */
            currency_code: string;
        };
        /** DepartmentOut */
        DepartmentOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "department" | "country" | "level" | "role";
        /**
         * EmployeeCreate
         * @description A new hire. Their first salary record (reason=hire) is created with them.
         */
        EmployeeCreate: {
            /** Employee Code */
            employee_code: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Department Id */
            department_id: number;
            /** Role Id */
            role_id: number;
            /** Level Id */
            level_id: number;
            /** Country Id */
            country_id: number;
            /** Manager Id */
            manager_id?: number | null;
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            /** @default active */
            status: components["schemas"]["EmployeeStatus"];
            /**
             * Base Amount
             * @description annual, local currency
             */
            base_amount: number | string;
            /**
             * Bonus Amount
             * @description annual, local currency
             * @default 0
             */
            bonus_amount: number | string;
        };
        /** EmployeeDetail */
        EmployeeDetail: {
            /** Id */
            id: number;
            /** Employee Code */
            employee_code: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            status: components["schemas"]["EmployeeStatus"];
            department: components["schemas"]["DepartmentOut"];
            role: components["schemas"]["RoleOut"];
            level: components["schemas"]["LevelOut"];
            country: components["schemas"]["CountryOut"];
            manager: components["schemas"]["EmployeeRef"] | null;
            current_salary: components["schemas"]["SalaryRecordOut"] | null;
            /** @description current base pay after tax; null if no salary */
            net_pay: components["schemas"]["NetPay"] | null;
            /** @description current base pay against the band that applies today; null if none */
            pay_assessment: components["schemas"]["PayAssessment"] | null;
            /**
             * Salary History
             * @description newest first
             */
            salary_history: components["schemas"]["SalaryRecordOut"][];
        };
        /**
         * EmployeeFilterOptions
         * @description Everything the list screen needs to render its filter controls.
         */
        EmployeeFilterOptions: {
            /** Departments */
            departments: components["schemas"]["DepartmentOut"][];
            /** Roles */
            roles: components["schemas"]["RoleOut"][];
            /** Levels */
            levels: components["schemas"]["LevelOut"][];
            /** Countries */
            countries: components["schemas"]["CountryOut"][];
            /** Statuses */
            statuses: components["schemas"]["EmployeeStatus"][];
            /** Salary Usd Min */
            salary_usd_min: string | null;
            /** Salary Usd Max */
            salary_usd_max: string | null;
        };
        /**
         * EmployeeListItem
         * @description Flat read model for one row of the list: employee + names + current pay.
         */
        EmployeeListItem: {
            /** Id */
            id: number;
            /** Employee Code */
            employee_code: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Department Id */
            department_id: number;
            /** Department */
            department: string;
            /** Role Id */
            role_id: number;
            /** Role */
            role: string;
            /** Level Id */
            level_id: number;
            /** Level */
            level: string;
            /** Country Id */
            country_id: number;
            /** Country Code */
            country_code: string;
            status: components["schemas"]["EmployeeStatus"];
            /**
             * Hire Date
             * Format: date
             */
            hire_date: string;
            /** Currency Code */
            currency_code: string;
            /** Base Amount */
            base_amount: string;
            /** Bonus Amount */
            bonus_amount: string;
            /** Base Amount Usd */
            base_amount_usd: string;
        };
        /** EmployeeRef */
        EmployeeRef: {
            /** Id */
            id: number;
            /** Employee Code */
            employee_code: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * EmployeeSort
         * @enum {string}
         */
        EmployeeSort: "name" | "employee_code" | "hire_date" | "department" | "country" | "level" | "base_salary_usd";
        /**
         * EmployeeStatus
         * @enum {string}
         */
        EmployeeStatus: "active" | "on_leave" | "terminated";
        /**
         * EmployeeUpdate
         * @description Partial profile update. Pay changes go through a salary revision instead.
         *
         *     Only fields present in the request are applied; send manager_id: null to clear it.
         */
        EmployeeUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Department Id */
            department_id?: number | null;
            /** Role Id */
            role_id?: number | null;
            /** Level Id */
            level_id?: number | null;
            /** Country Id */
            country_id?: number | null;
            /** Manager Id */
            manager_id?: number | null;
            status?: components["schemas"]["EmployeeStatus"] | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** GroupKey */
        GroupKey: {
            /**
             * Id
             * @description null for the whole population
             */
            id: number | null;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Min Years */
            min_years: number;
            /** Max Years */
            max_years: number | null;
        };
        /**
         * NetPay
         * @description Current base pay after the flat tax deduction, in the salary's local currency.
         */
        NetPay: {
            /** Currency Code */
            currency_code: string;
            /** Base Amount */
            base_amount: string;
            /**
             * Tax Rate
             * @description fraction deducted, e.g. 0.10
             */
            tax_rate: string;
            /** Tax Amount */
            tax_amount: string;
            /**
             * Net Amount
             * @description base_amount - tax_amount
             */
            net_amount: string;
        };
        /** OutOfBandEmployee */
        OutOfBandEmployee: {
            /** Employee Id */
            employee_id: number;
            /** Employee Code */
            employee_code: string;
            /** Full Name */
            full_name: string;
            /** Department */
            department: string;
            /** Role */
            role: string;
            /** Level */
            level: string;
            /** Country Code */
            country_code: string;
            /** Currency Code */
            currency_code: string;
            /** Base Amount */
            base_amount: string;
            assessment: components["schemas"]["PayAssessment"];
        };
        /**
         * OutOfBandFilter
         * @enum {string}
         */
        OutOfBandFilter: "below" | "above" | "outside";
        /** Page[BandOut] */
        Page_BandOut_: {
            /** Items */
            items: components["schemas"]["BandOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[EmployeeListItem] */
        Page_EmployeeListItem_: {
            /** Items */
            items: components["schemas"]["EmployeeListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[OutOfBandEmployee] */
        Page_OutOfBandEmployee_: {
            /** Items */
            items: components["schemas"]["OutOfBandEmployee"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * PayAssessment
         * @description Where one employee's base pay sits against the band that applies to them.
         */
        PayAssessment: {
            band: components["schemas"]["BandRef"];
            /** Salary In Band Currency */
            salary_in_band_currency: string;
            /** Compa Ratio */
            compa_ratio: string;
            position: components["schemas"]["BandPosition"];
            /**
             * Gap Amount
             * @description distance outside the band, band currency; 0 inside
             */
            gap_amount: string;
            /**
             * Gap Pct
             * @description gap as a percent of the breached boundary; 0 inside
             */
            gap_pct: string;
        };
        /** PaySummary */
        PaySummary: {
            /** Headcount */
            headcount: number;
            /**
             * Payroll Cost Usd
             * @description annual base + bonus, USD
             */
            payroll_cost_usd: string;
            base_salary_usd: components["schemas"]["SalaryStats"];
            band_compliance: components["schemas"]["BandCompliance"];
            /** Compa Ratio Median */
            compa_ratio_median: string | null;
            /**
             * Fx As Of
             * @description date of the FX snapshot behind every USD figure
             */
            fx_as_of: string | null;
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Department Id */
            department_id: number;
        };
        /** SalaryRecordOut */
        SalaryRecordOut: {
            /** Id */
            id: number;
            /** Currency Code */
            currency_code: string;
            /** Base Amount */
            base_amount: string;
            /** Bonus Amount */
            bonus_amount: string;
            /** Fx Rate To Usd */
            fx_rate_to_usd: string;
            /** Base Amount Usd */
            base_amount_usd: string;
            /** Bonus Amount Usd */
            bonus_amount_usd: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Is Current */
            is_current: boolean;
            reason: components["schemas"]["ChangeReason"];
            /** Note */
            note: string | null;
            /** Band Id */
            band_id: number | null;
        };
        /**
         * SalaryRevisionCreate
         * @description New pay from effective_from onwards. The current record is closed, not edited.
         */
        SalaryRevisionCreate: {
            /**
             * Base Amount
             * @description annual, local currency
             */
            base_amount: number | string;
            /**
             * Bonus Amount
             * @description annual, local currency
             * @default 0
             */
            bonus_amount: number | string;
            /**
             * Currency Code
             * @description optional check: must be the employee's country currency
             */
            currency_code?: string | null;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "promotion" | "merit" | "market_adjustment" | "correction";
            /** Note */
            note?: string | null;
        };
        /** SalaryRevisionOut */
        SalaryRevisionOut: {
            previous: components["schemas"]["SalaryRecordOut"];
            current: components["schemas"]["SalaryRecordOut"];
            /**
             * Base Change Pct
             * @description change in base pay, percent, 2 dp
             */
            base_change_pct: string;
        };
        /**
         * SalaryStats
         * @description Annual base pay in USD across the group.
         */
        SalaryStats: {
            /** Avg */
            avg: string | null;
            /** Median */
            median: string | null;
            /** Min */
            min: string | null;
            /** Max */
            max: string | null;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: {
                /** @description name, code or email */
                q?: string | null;
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
                status?: components["schemas"]["EmployeeStatus"] | null;
                /** @description current base, USD */
                min_salary_usd?: number | string | null;
                /** @description current base, USD */
                max_salary_usd?: number | string | null;
                sort?: components["schemas"]["EmployeeSort"];
                order?: components["schemas"]["SortOrder"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EmployeeListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_api_v1_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    employee_filter_options_api_v1_employees_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeFilterOptions"];
                };
            };
        };
    };
    get_employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_api_v1_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revise_salary_api_v1_employees__employee_id__salary_revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalaryRevisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalaryRevisionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_bands_api_v1_bands_get: {
        parameters: {
            query?: {
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
                scope?: components["schemas"]["BandScope"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BandOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_band_api_v1_bands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BandCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_band_api_v1_bands__band_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                band_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_band_api_v1_bands__band_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                band_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_band_api_v1_bands__band_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                band_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BandUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pay_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: {
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_breakdown_api_v1_analytics_breakdown_get: {
        parameters: {
            query: {
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
                by: components["schemas"]["Dimension"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compa_ratio_distribution_api_v1_analytics_compa_ratio_get: {
        parameters: {
            query?: {
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
                by?: components["schemas"]["Dimension"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaRatioDistribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    band_compliance_api_v1_analytics_band_compliance_get: {
        parameters: {
            query?: {
                department_id?: number | null;
                role_id?: number | null;
                level_id?: number | null;
                country_id?: number | null;
                position?: components["schemas"]["OutOfBandFilter"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OutOfBandEmployee_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
